---
apiVersion: v1
kind: Namespace
metadata:
  name: dvwa-lab
---
apiVersion: v1
kind: Secret
metadata:
  name: dvwa-secret
  namespace: dvwa-lab
type: Opaque
data:

  MYSQL_ROOT_PASSWORD: Rishigrt
  MYSQL_PASSWORD: Rishigrt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvwa-mysql-pvc
  namespace: dvwa-lab
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-mysql
  namespace: dvwa-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-mysql
  template:
    metadata:
      labels:
        app: dvwa-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: dvwa
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: dvwa-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-mysql
  namespace: dvwa-lab
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: dvwa-mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-web
  namespace: dvwa-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-web
  template:
    metadata:
      labels:
        app: dvwa-web
    spec:
      containers:
      - name: dvwa
        image: cytopia/dvwa:latest
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: dvwa
        - name: MYSQL_HOST
          value: dvwa-mysql
        - name: PHP_DISPLAY_ERRORS
          value: "0"
        - name: SECURITY_LEVEL
          value: "medium"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-web
  namespace: dvwa-lab
spec:
  selector:
    app: dvwa-web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
